crafting:
  LEATHER_HELMET: 5 LEATHER
  LEATHER_CHESTPLATE: 8 LEATHER
  LEATHER_LEGGINGS: 7 LEATHER
  LEATHER_BOOTS: 4 LEATHER

  STONE_AXE: 3 COBBLESTONE
  STONE_HOE: 2 COBBLESTONE
  STONE_PICKAXE: 3 COBBLESTONE
  STONE_SPADE: 1 COBBLESTONE
  STONE_SWORD: 2 COBBLESTONE

  DIAMOND_AXE: 3 DIAMOND
  DIAMOND_HOE: 2 DIAMOND
  DIAMOND_PICKAXE: 3 DIAMOND
  DIAMOND_SPADE: 1 DIAMOND
  DIAMOND_SWORD: 2 DIAMOND
  DIAMOND_HELMET: 5 DIAMOND
  DIAMOND_CHESTPLATE: 8 DIAMOND
  DIAMOND_LEGGINGS: 7 DIAMOND
  DIAMOND_BOOTS: 4 DIAMOND

furnace:
  IRON_AXE: 3 IRON_INGOT
  IRON_HOE: 2 IRON_INGOT
  IRON_PICKAXE: 3 IRON_INGOT
  IRON_SPADE: 1 IRON_INGOT
  IRON_SWORD: 2 IRON_INGOT
  IRON_HELMET: 5 IRON_INGOT
  IRON_CHESTPLATE: 8 IRON_INGOT
  IRON_LEGGINGS: 7 IRON_INGOT
  IRON_BOOTS: 4 IRON_INGOT

  CHAINMAIL_HELMET: 5 IRON_INGOT
  CHAINMAIL_CHESTPLATE: 8 IRON_INGOT
  CHAINMAIL_LEGGINGS: 7 IRON_INGOT
  CHAINMAIL_BOOTS: 4 IRON_INGOT

  GOLD_AXE: 3 GOLD_INGOT
  GOLD_HOE: 2 GOLD_INGOT
  GOLD_PICKAXE: 3 GOLD_INGOT
  GOLD_SPADE: 1 GOLD_INGOT
  GOLD_SWORD: 2 GOLD_INGOT
  GOLD_HELMET: 5 GOLD_INGOT
  GOLD_CHESTPLATE: 8 GOLD_INGOT
  GOLD_LEGGINGS: 7 GOLD_INGOT
  GOLD_BOOTS: 4 GOLD_INGOT
